export const WishRecommendation = {
  totalPages: 0,
  totalElements: 1,
  contents: [
    {
      id: 1,
      title: "Need Mobile phone",
      byDate: "2020-06-26",
      minBudget: 20000,
      maxBudget: 50000,
      description: "I want best mobile .... ",
      created: "2020-07-20T04:06:04.452Z",
      updated: "2020-07-20T04:06:04.452Z",
      status: "REVIEWED",
      agent:{"name":"Wishgee Admin","email":"admin@wishgee.com","profile":"http://admin"},
      customer:{"id":24,"name":"Sudip Bhandari"},
      response: [
        {
          productName: "iPhone",
          productPrice: 110000,
          productBrand: "Apple",
          productType: "phone",
          productLink: "https://www.apple.com/in/iphone/",
          productThumbnail: "https://www.apple.com/in/iphone/",
          closingRemark: "Closing Mark qqqqq",
          alternateResult: "Alternate result ",
          keywords: "Processing | fast | 3gb RAM",
          agent: {
            name: "Modi Ji",
            email: "support@wishgee.com",
            mobile: "+19253248989",
          },
        },
      ],
      type: {
        id: 1,
        name: "Mobile",
        createdTime: "2020-07-20T04:06:04.452Z",
        updatedTime: "2020-07-20T04:06:04.452Z",
      },
    },
  ],
};

export const WishTypeList = {
  totalPages: 0,
  totalElements: 2,
  contents: [
    {
      id: "1",
      name: "phone",
      keywords: "mobile phone cell",
      img: "./products/phone.svg",
      alt: "phone",
    },
    {
      id: 2,
      name: "washing machine",
      keywords: ["washing machine"],
      img: "./products/washing-machine.svg",
      alt: "washing machine",
    },
    {
      id: 3,
      name: "fridge",
      keywords: "fridge refrigerator",
      img: "./products/fridge.svg",
      alt: "fridge",
    },
    {
      id: 4,
      name: "camera",
      keywords: "digital camera",
      img: "./products/camera.svg",
      alt: "camera",
    },
    {
      id: 5,
      name: "cycle",
      keywords: "bicycle gear",
      img: "./products/cycle.svg",
      alt: "cycle",
    },
    {
      id: 6,
      name: "drone",
      keywords: "drone",
      img: "./products/drone.svg",
      alt: "drone",
    },
    {
      id: 7,
      name: "guitar",
      keywords: "electric base guitar",
      img: "./products/guitar.svg",
      alt: "guitar",
    },
    {
      id: 8,
      name: "shoes",
      keywords: "sneakers sports shoes footwear",
      img: "./products/shoes.svg",
      alt: "shoes",
    },
    {
      id: 9,
      name: "speaker",
      keywords: "bluetooth wireless speakers",
      img: "./products/speaker.svg",
      alt: "speaker",
    },
    {
      id: 10,
      name: "ipad",
      keywords: "ipad apple tablet",
      img: "./products/ipad.svg",
      alt: "ipad",
    },
    {
      id: 11,
      name: "laptop",
      keywords: "laptop desktop",
      img: "./products/laptop.svg",
      alt: "laptop",
    },
    {
      id: 12,
      name: "inverter",
      keywords: "ups power backup home",
      img: "./products/inverter.svg",
      alt: "inverter",
    },
    {
      id: 13,
      name: "earphones",
      keywords: "bluetooth headphones wired wireless earphones",
      img: "./products/earphones.svg",
      alt: "earphones",
    },
  ],
};

export const RecentResults =  {totalPages: 0,
totalElements: 2,
contents: [
    {
      id: "123",
      productName: "iPhone",
      productPrice: 110000,
      productBrand: "Apple",
      productType: "phone",
      productLink: "https://www.apple.com/in/iphone/",
      productThumbnail: "https://www.apple.com/in/iphone/",
      closingRemark: "Closing Mark qqqqq",
      alternateResult: "Alternate result ",
      keywords: "Processing | fast | 3gb RAM",
      agent: {
        name: "Modi Ji",
        email: "support@wishgee.com",
        mobile: "+19253248989",
      },
    },
    {
      id: "124",
      productName: "MI Phone",
      productPrice: 110000,
      productBrand: "Xiaomi",
      productType: "phone",
      productLink: "https://www.apple.com/in/iphone/",
      productThumbnail: "https://www.apple.com/in/iphone/",
      closingRemark: "Closing Mark qqqqq",
      alternateResult: "Alternate result ",
      keywords: "Processing | fast | 3gb RAM",
      agent: {
        name: "Modi Ji",
        email: "support@wishgee.com",
        mobile: "+19253248989",
      },
    }
  ]
}
